// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAulqFDt_jidIMW4jeeA-Bqf2Vd7uGeYx4',
    appId: '1:702791169587:web:283f488330851eeb825546',
    messagingSenderId: '702791169587',
    projectId: 'rost-new-6d4db',
    authDomain: 'rost-new-6d4db.firebaseapp.com',
    storageBucket: 'rost-new-6d4db.firebasestorage.app',
    measurementId: 'G-X0JR97FL3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEbfD7zCuXdGDI4qJhRTHyQP0hNyg6qkQ',
    appId: '1:702791169587:android:0377f27ec9237c07825546',
    messagingSenderId: '702791169587',
    projectId: 'rost-new-6d4db',
    storageBucket: 'rost-new-6d4db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh2MlnSIXsj7Kkd6AG9P_GYna2tU4K_HE',
    appId: '1:702791169587:ios:28b14f6f3d22f3dd825546',
    messagingSenderId: '702791169587',
    projectId: 'rost-new-6d4db',
    storageBucket: 'rost-new-6d4db.firebasestorage.app',
    iosBundleId: 'com.example.rost',
  );
}
